fix: processing groups serialization (#3522)
fixes the issue:

```
  File "/app/.pixi/envs/fmriprep/lib/python3.12/site-packages/fmriprep/config.py", line 810, in dumps
    settings['execution']['processing_groups'] = _serialize_pg(pg)
                                                 ^^^^^^^^^^^^^^^^^
  File "/app/.pixi/envs/fmriprep/lib/python3.12/site-packages/fmriprep/config.py", line 870, in _serialize_pg
    val[1] = [val[1]]
    ~~~^^^
TypeError: 'tuple' object does not support item assignment
```

should look into adding a sessionwise test to the ci